### ISSUE TITLE
Please Make ASCII Text using the .DW pseudo-opcode work

### ISSUE THREAD

**Issue by TheRealHamtaro126** [nicklausw/asm16#3]
This is meant for doing better 65816/SNES Text.
 
We need to have added support for the .DW/.WORD statement for such ASCII strings. This includes the math for attributes and properties that can be defined too.

Example case: The SNES version of Stripe Image Format, for use in some Hacks and Homebrews, Uses .DW/.WORD instead of .DB/.BYTE for the Tilemap data.

Such as the case with this test:

> ATBlue = $3800 ;Attribute is Blue, or $38, The ASCII offset is $00
>
> ;ASM16 creates an error because it is not implemented as of yet!!!
> .DW "TEXT TEST!"+ATBlue

**Comment by nicklausw** [comment]
Could be a case of copying some of DB's code to DW. Let's find out.

**Comment by nicklausw** [comment]
How about I make a separate directive for this?
```
.tw $3800, "TEXT TEST!"
```
.TW (Text Word) adds the first argument to each character of the second one, outputs each result word-size. How's that? Sorry, this is a behavior too peculiar to be a part of .DW.

**Comment by TheRealHamtaro126** [comment]
Sounds good enough to Implement!

**Comment by nicklausw** [comment]
Try using TW like exemplified above. It's in the latest sources and my minimal tests show success, but just to be safe.

**Comment by TheRealHamtaro126** [comment]
It works, Can't find any glitches and/or bugs as far as I am aware of. This will now be closed!
